Add uninstall after connectedCheck
./gradlew connectedCheck --stacktrace
AND
./gradlew :android-core:cAT :android-kit-base:cAT

Share
:testutils:packageDebugAndroidTest
:testutils:connectedDebugAndroidTest
:testutils:connectedAndroidTest

Which may be causing:
Failed to install APK(s): /home/runner/work/mparticle-android-sdk/mparticle-android-sdk/android-core/build/outputs/apk/androidTest/debug/android-core-debug-androidTest.apk
INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.mparticle.test signatures do not match previously installed version; ignoring!
com.android.ddmlib.InstallException: INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.mparticle.test signatures do not match previously installed version; ignoring!